[features]
seeds = false

[programs.devnet]
hello_clockwork = "6QVya5igRah5B256GyUZxcM3uTZxjYatRuLxXDLAh7cc"

[programs.localnet]
hello_clockwork = "6QVya5igRah5B256GyUZxcM3uTZxjYatRuLxXDLAh7cc"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
