[features]
seeds = false

[programs.localnet]
distributor = "ARdMXW5cuNAoNmtCDfrJRYStNXsHgc6yeapTkz9YAYSq"

[programs.devnet]
distributor = "ARdMXW5cuNAoNmtCDfrJRYStNXsHgc6yeapTkz9YAYSq"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
