[features]
seeds = false
[programs.localnet]
distributor = "CuiekNJo4J4SbDVCyvuzs5qAxE1bdmbQUUR71w18bxUa"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
