[features]
seeds = false
[programs.localnet]
distributor = "G3X9SZaKsqHvKX2xfHPa7dpj9DFAZu3VuGQ1c2jQweZu"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
