[features]
seeds = false
skip-lint = false

[programs.mainnet]
openbook_dca = "6mrizDvtdQdg5J79GRCbBDZvmKjDjwuUcZNM5zj4TGdD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
