[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_clockwork = "Gj5eCcUsKAPAJMftoKK8bLKCSByTaWANQzrESeWZT5Qe"
[programs.devnet]
hello_clockwork = "Gj5eCcUsKAPAJMftoKK8bLKCSByTaWANQzrESeWZT5Qe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
