[features]
seeds = false
skip-lint = false

[programs.localnet]
payments = "BvpYVck2GmCcoHrvtj1UDZ76xACcW1fP4HeUgCZKqiCP"

[programs.devnet]
payments = "BvpYVck2GmCcoHrvtj1UDZ76xACcW1fP4HeUgCZKqiCP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/amir/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
