[features]
seeds = false
skip-lint = false
[programs.localnet]
cpi = "GJdG9TCR1Rj8FqAdnahZHudJUZ9h2PpdkDQsbbDxSTof"
[programs.devnet]
cpi = "GJdG9TCR1Rj8FqAdnahZHudJUZ9h2PpdkDQsbbDxSTof"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
