[features]
seeds = false
skip-lint = false

[programs.mainnet]
orca_dca = "DjKusZzdgdobu1yrh2qKLdcabzWRDLGECcajgfm2VCSJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
