[package]
name = "pyth_stats_client"
version = "0.1.0"
edition = "2021"


[dependencies]
anchor-lang = "0.26.0"
clockwork-client = "1.4.0" 
pyth_stats = { path = "../programs/pyth_stats", features = ["no-entrypoint"], version = "0.1.0" }
solana-sdk = "1.13.5"

[features]
mainnet = []