[features]
seeds = false

[programs.localnet]
serum_crank = "Anqpb1dsueVvZr9xNweptWbzrAJiZYwAcHg9XoXoKsQ1"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
