[features]
seeds = false
skip-lint = false

[programs.mainnet]
openbook_dca = "B9JNaF9toUNv2Dkj8WEUMMybzfrFwREq7YMno2ht3Uhj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
