[features]
seeds = false
skip-lint = false
[programs.devnet]
subscriptions_program = "Dhznaw95UUbADF49e4AXqjFo56nTFttFUtWU3ptEN7Ch"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
