[package]
name = "pyth_stats"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "pyth_stats"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.26.0"
bytemuck = "1.12.3"
clockwork-sdk = "1.4.0"
pyth-sdk-solana = "0.7.0"

