[package]
name = "openbook-dca"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "openbook_dca"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-spl = { version = "0.26.0", features = ["dex"] }
anchor-lang = { version = "0.26.0", features = ["init-if-needed"] }
clockwork-sdk = "1.4.2"
safe-transmute = "0.11.0"